version: '3.3'

services:
  web:
    container_name : frontend-ti-monitoramento-folha-contabilizacao
    restart: always
    build: .
    ports:
      - 8080:8080
    expose:
      - "8080"

